app/controllers/guesses_controller.rb
test/controllers/guesses_controller_test.rb

guesses controller

---

app/controllers/game_sessions_controller.rb
app/views/game_sessions/create.html.erb
app/views/game_sessions/show.html.erb
config/routes.rb
test/controllers/game_sessions_controller_test.rb

controller game sessions

---

app/assets/lyrics/auvergnat.txt
app/assets/lyrics/caravane.txt
app/assets/lyrics/confessionnocturne.txt
app/assets/lyrics/da.txt
app/assets/lyrics/dernieredanse.txt
app/assets/lyrics/djadja.txt
app/assets/lyrics/dommage.txt
app/assets/lyrics/doubleje.txt
app/assets/lyrics/jeuneetcon.txt
app/assets/lyrics/jour.txt
app/assets/lyrics/lesroisdumonde.txt
app/assets/lyrics/lesyeuxdisent.txt
app/assets/lyrics/letempsestbon.txt
app/assets/lyrics/maisjetaime.txt
app/assets/lyrics/maphilosophie.txt
app/assets/lyrics/odeurdessence.txt
app/assets/lyrics/papaoutai.txt
app/assets/lyrics/parcequonvientdeloin.txt
app/assets/lyrics/quelqunmadit.txt
app/assets/lyrics/tamariniere.txt
app/assets/lyrics/toutoublier.txt
db/seeds.rb

fait avec le test pour voire les paroles des chansons

 les seed ajouttées avec soin

---

app/controllers/application_controller.rb
app/controllers/game_sessions_controller.rb
app/controllers/guesses_controller.rb
app/controllers/pages_controller.rb
app/views/pages/home.html.erb
db/seeds.rb

don't panic lots indents modified
add 2 btns

Btn solo and form playlist mode

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Front home final

---

app/views/pages/home.html.erb

L'url du logo ne marche pas dans Heroku, mais ok en local.
Je l'ai mise en absolu (../../assets/logo-smile.png) et ça fonctionne en local. Je vais push pour voir si ok en Heroku

Correction de l'url du logo

---

app/assets/stylesheets/components/_bubble.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/pages/_faq.scss
app/assets/stylesheets/pages/_show.scss
app/javascript/controllers/guess_chart_controller.js
app/views/game_sessions/show.html.erb

game-screen-v2

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_index.scss
app/assets/stylesheets/pages/_rules.scss
app/assets/stylesheets/pages/_victory.scss
app/views/pages/rules.html.erb
app/views/shared/_navbar.html.erb

Few changing, custom navbar, changing code html because few errors and indent, conflict with app

Rules screen bubble & navbar done

---

app/assets/stylesheets/components/_bubble.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/pages/_show.scss
app/views/game_sessions/show.html.erb

game-screen-v3

---

app/assets/stylesheets/pages/_home.scss
app/views/game_sessions/show.html.erb
app/views/pages/home.html.erb

home button down

---

app/assets/stylesheets/components/_carousel.scss

stats-screen-v2

---

app/assets/stylesheets/components/_bubble.scss
app/assets/stylesheets/components/_carousel.scss
app/assets/stylesheets/pages/_faq.scss
app/assets/stylesheets/pages/_rules.scss
app/assets/stylesheets/pages/_show.scss
app/assets/stylesheets/pages/_stats.scss
app/models/game_session_song.rb
app/views/game_sessions/show.html.erb
app/views/game_sessions/victory.html.erb
app/views/guests/stats.html.erb

front-game-and-stats-val

---

app/assets/stylesheets/components/_button.scss
app/controllers/game_sessions_controller.rb
app/views/game_sessions/show.html.erb
app/views/game_sessions/victory.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
package-lock.json
package.json
yarn.lock

lyrics-reveal

---

app/assets/stylesheets/components/_button.scss
app/javascript/controllers/confettis_controller.js
app/models/song.rb
app/views/game_sessions/victory.html.erb
app/views/guests/stats.html.erb
app/views/pages/faq.html.erb
app/views/pages/home.html.erb
app/views/pages/rules.html.erb

css animate done

---

app/views/pages/rules.html.erb

pour dire a l'utilisateur de s'enregistrer et jouer avec ses amis

comment jouer avec les amis

---

app/assets/lyrics/dernieredanse.txt
app/assets/lyrics/dommage.txt
app/assets/lyrics/lesyeuxdisent.txt
app/assets/lyrics/letempsestbon.txt
app/assets/lyrics/papaoutai.txt

les div ontt été suppriméess des seed et chaque chanson a été vérifiée

nettoyées de div

---

config/routes.rb
test/controllers/devise_controller_test.rb

fix refresh on the devise tricky on routes

---

app/assets/stylesheets/pages/_signup.scss
app/views/devise/confirmations/new.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb

sign in fix done

---

app/assets/stylesheets/pages/_rules.scss
app/assets/stylesheets/pages/_show.scss
app/assets/stylesheets/pages/_signup.scss
app/controllers/friendships_controller.rb
app/views/guesses/_form.html.erb
app/views/pages/rules.html.erb

detail-front-v1

---

app/views/pages/home.html.erb

home user welcome

---

app/assets/stylesheets/components/_bubble.scss
app/assets/stylesheets/pages/_faq.scss
app/views/game_sessions/victory.html.erb
app/views/pages/faq.html.erb

overflow faq
